version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/orcid-publications-manager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/tools/Metaculus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/humanaios-funding-pipeline"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
