#!/usr/bin/env python3
"""
reference_linter.py — v0.1 (proof-of-concept, real run, not simulated)

Generalizes primary_check_gate_v1_0.py's discipline (no code claim admissible
without a real VerificationRecord) to a different claim type: a governance
document's own canonical-URL pointers. Sweeps every raw.githubusercontent.com
reference across a set of source files, live-fetches each one, and reports
LIVE / DEAD / UNCHECKED — no claim about "this file is canonical" is trusted
without actually being fetched this run.

This is deliberately narrow (v0.1): URL extraction is a regex over one
domain pattern, not a general claim grammar. That's the honest scope limit —
see the write-up, not this docstring, for what a v0.2 claim-grammar version
would need to add.
"""

from __future__ import annotations

import re
import sys
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

URL_PATTERN = re.compile(
    r"https://raw\.githubusercontent\.com/[A-Za-z0-9_-]+/[A-Za-z0-9_-]+/main/[A-Za-z0-9_./-]+\.(?:md|yaml|yml|json)"
)


class VerificationRecord:
    """Mirrors the tool's own naming convention deliberately — a claim about
    a URL's liveness is not admissible without one of these, generated by
    an actual fetch performed in this run."""
    def __init__(self, url: str, source_file: str, http_status: int, checked_at: str):
        self.url = url
        self.source_file = source_file
        self.http_status = http_status
        self.checked_at = checked_at
        self.verdict = "LIVE" if http_status == 200 else "DEAD"

    def to_dict(self):
        return {
            "url": self.url, "source_file": self.source_file,
            "http_status": self.http_status, "verdict": self.verdict,
            "checked_at": self.checked_at,
        }


def extract_references(path: Path) -> list:
    text = path.read_text(encoding="utf-8")
    return sorted(set(URL_PATTERN.findall(text)))


def fetch_status(url: str) -> int:
    """Real HTTP call, not a stub. Uses curl since it's already on the
    allowlisted path for this environment."""
    result = subprocess.run(
        ["curl", "-sL", "-o", "/dev/null", "-w", "%{http_code}", url],
        capture_output=True, text=True, timeout=15,
    )
    try:
        return int(result.stdout.strip())
    except ValueError:
        return -1


def lint(source_paths: list) -> list:
    records = []
    checked_urls = set()
    now = datetime.now(timezone.utc).isoformat()

    for path in source_paths:
        p = Path(path)
        if not p.exists():
            print(f"  SKIP (not found): {path}", file=sys.stderr)
            continue
        refs = extract_references(p)
        for url in refs:
            if url in checked_urls:
                continue  # each unique URL checked once per run, not once per citing file
            checked_urls.add(url)
            status = fetch_status(url)
            records.append(VerificationRecord(url, p.name, status, now))

    return records


if __name__ == "__main__":
    sources = ["CURRENT.md", "GOVERNANCE.md", "SEED.md", "SESSION_RITUALS.md"]
    print(f"reference_linter v0.1 — real fetch against {len(sources)} source files\n")

    records = lint(sources)

    live = [r for r in records if r.verdict == "LIVE"]
    dead = [r for r in records if r.verdict == "DEAD"]

    for r in records:
        marker = "✓" if r.verdict == "LIVE" else "✗ DEAD"
        print(f"  [{r.http_status:>3}] {marker:8} {r.url}")

    print(f"\n{len(live)} LIVE, {len(dead)} DEAD, {len(records)} total unique references checked")

    if dead:
        print("\nDEAD references — cited as canonical but do not resolve:")
        for r in dead:
            print(f"  {r.url}")

    out = Path("reference_lint_report.json")
    out.write_text(json.dumps([r.to_dict() for r in records], indent=2))
    print(f"\nFull VerificationRecord log: {out}")
