from __future__ import annotations
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "tools" / "pr_challenge_dialogue_router_v0_1.py"
spec = importlib.util.spec_from_file_location("challenge_router", TOOL)
assert spec and spec.loader
router = importlib.util.module_from_spec(spec)
spec.loader.exec_module(router)

HEAD = "a" * 40

def audit_body():
    return f"""## RED TEAM AUDIT
**Auditor Origin:** Claude Code
**Audited HEAD SHA:** `{HEAD}`
**Authority Effect:** NONE
#### FIND-001: in scope
**Affected Artifact:** `tools/a.py`
#### FIND-002: outside diff
**Affected Artifact:** `docs/other.md`
_Generated by [Claude Code](https://claude.ai/code)_
"""

def event(body, comment_id=101):
    return {"action": "created", "issue": {"number": 630, "pull_request": {}},
            "comment": {"id": comment_id, "body": body}}

def route(body, comments=None, head=HEAD):
    return router.route(event=event(body), changed_files={"tools/a.py"},
                        existing_comments=comments or [], current_head=head,
                        repository="humanaios-ui/operations", pilot_pr=630)

def test_positive_claude_marker_routes_shared_carrier_turn():
    result = route(audit_body())
    assert result["should_reply"] is True
    assert result["state"] == "AUDIT_RECEIVED"

def test_prompt_does_not_self_trigger():
    assert route("@claude please audit") == {
        "should_reply": False, "reason": "not_positive_claude_turn"
    }

def test_scope_uses_changed_files():
    rows = {x["finding_id"]: x for x in route(audit_body())["findings"]}
    assert rows["FIND-001"]["router_scope"] == "IN_SCOPE_PR630_FINDING"
    assert rows["FIND-002"]["router_scope"] == "OUT_OF_SCOPE_REPOSITORY_FINDING"

def test_head_mismatch_stops_translation():
    result = route(audit_body(), head="b" * 40)
    assert result["state"] == "HEAD_MISMATCH"
    assert "No findings are translated forward automatically" in result["comment"]

def test_source_comment_idempotency():
    first = route(audit_body())
    second = route(audit_body(), comments=[{"body": first["comment"]}])
    assert second == {"should_reply": False, "reason": "duplicate_source_comment"}

def test_scope_correction_advances():
    body = f"""Auditor Origin: Claude Code
Generated by Claude Code
conversation_id: PR630-REDTEAM-001
turn_type: SCOPE_CORRECTION
audited_head: {HEAD}
authority_effect: NONE
"""
    assert route(body)["next_turn"] == "EVIDENCE_CHALLENGE"

def test_disposition_terminates_without_mention():
    body = f"""Auditor Origin: Claude Code
Generated by Claude Code
conversation_id: PR630-REDTEAM-001
turn_type: DISPOSITION
audited_head: {HEAD}
authority_effect: NONE
"""
    result = route(body)
    assert result["next_turn"] == "COMPLETE"
    assert "@claude" not in result["comment"]

def test_non_none_authority_is_malformed():
    body = f"""Auditor Origin: Claude Code
Generated by Claude Code
conversation_id: PR630-REDTEAM-001
turn_type: SCOPE_CORRECTION
audited_head: {HEAD}
authority_effect: MERGE
"""
    assert route(body)["state"] == "MALFORMED_TURN"
