"""
OI-BRIDGE-01 Phase 1 — Escalation Contract

Handles HUMAN_REQUIRED escalations with Z2 decision window.
Posts GitHub comments, awaits Z2 response, logs to NF_LEDGER.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime, timezone, timedelta


@dataclass
class Escalation:
    """HUMAN_REQUIRED escalation record."""
    message_id: str
    reason: str
    context: str
    escalated_at: str  # ISO8601 UTC
    timeout_at: str  # ISO8601 UTC (48h window)
    z2_tag: str  # "@Night" or similar
    github_comment_url: Optional[str] = None
    z2_response: Optional[str] = None
    z2_response_at: Optional[str] = None


class EscalationContract:
    """Manage HUMAN_REQUIRED escalations to Z2."""

    Z2_DECISION_WINDOW_HOURS = 48
    Z2_TAG = "@Night"  # GitHub mention for Z2
    Z2_USERNAME = "night-z2"

    def __init__(self, github_transport=None, ledger_writer=None):
        """
        Initialize escalation contract.

        Args:
            github_transport: GitHub API client
            ledger_writer: NF_LEDGER writer
        """
        self.github_transport = github_transport
        self.ledger_writer = ledger_writer
        self.escalations: dict[str, Escalation] = {}

    def escalate_to_human_required(self, message_id: str, pr_number: int,
                                  reason: str, context: str) -> Escalation:
        """
        Escalate message to HUMAN_REQUIRED.

        Posts GitHub comment tagging Z2.
        Sets 48h decision window.
        Logs escalation to NF_LEDGER.

        Args:
            message_id: Message identifier
            pr_number: GitHub PR number for comment posting
            reason: Escalation reason (SIGNATURE_INVALID, SCOPE_MISMATCH, etc.)
            context: Additional context for Z2

        Returns:
            Escalation record with timeout
        """
        now = datetime.now(timezone.utc)
        timeout = now + timedelta(hours=self.Z2_DECISION_WINDOW_HOURS)

        # Construct GitHub comment
        comment_body = self._build_escalation_comment(message_id, reason, context)

        # Post comment
        comment_url = None
        if self.github_transport:
            result = self.github_transport.post_comment(pr_number, comment_body)
            comment_url = result.get("url")

        # Create escalation record
        escalation = Escalation(
            message_id=message_id,
            reason=reason,
            context=context,
            escalated_at=now.isoformat(),
            timeout_at=timeout.isoformat(),
            z2_tag=self.Z2_TAG,
            github_comment_url=comment_url,
        )

        self.escalations[message_id] = escalation

        # Log to ledger
        if self.ledger_writer:
            self.ledger_writer.append_escalation(message_id, reason, "HUMAN_REQUIRED")

        return escalation

    def _build_escalation_comment(self, message_id: str, reason: str,
                                 context: str) -> str:
        """Build GitHub comment for escalation."""
        now = datetime.now(timezone.utc)
        timeout = (now + timedelta(hours=self.Z2_DECISION_WINDOW_HOURS)).isoformat()

        comment = f"""⚠️ **HUMAN_REQUIRED** — Escalation to Z2

{self.Z2_TAG} decision required on message `{message_id}`.

**Reason:** {reason}

**Context:**
```
{context}
```

**Decision Window:** 48 hours (by {timeout})

**Z2 Actions:**
1. Review the escalation reason and context above
2. Reply with decision:
   - `Z2 ACCEPT: <action>` — proceed with action
   - `Z2 EDIT: <changes>` — request changes
   - `Z2 REJECT: <reason>` — reject message

**Bridge Status:** Awaiting Z2 decision. Message held in HUMAN_REQUIRED state.

---
_Generated by [Claude Code](https://claude.ai/code)_
"""
        return comment

    def check_timeout(self, message_id: str) -> bool:
        """
        Check if escalation has exceeded 48h window.

        Args:
            message_id: Message identifier

        Returns:
            True if timeout exceeded
        """
        escalation = self.escalations.get(message_id)
        if not escalation:
            return False

        timeout = datetime.fromisoformat(escalation.timeout_at.replace('Z', '+00:00'))
        now = datetime.now(timezone.utc)

        return now > timeout

    def resolve_with_z2_decision(self, message_id: str, decision: str,
                                response_text: str) -> Escalation:
        """
        Record Z2 decision on escalation.

        Args:
            message_id: Message identifier
            decision: Z2 decision (ACCEPT, EDIT, REJECT)
            response_text: Z2's response text

        Returns:
            Updated Escalation
        """
        escalation = self.escalations.get(message_id)
        if not escalation:
            raise ValueError(f"Escalation not found: {message_id}")

        now = datetime.now(timezone.utc)
        escalation.z2_response = f"{decision}: {response_text}"
        escalation.z2_response_at = now.isoformat()

        # Log to ledger
        if self.ledger_writer:
            self.ledger_writer.append_event("Z2_DECISION", {
                "message_id": message_id,
                "decision": decision,
                "response_at": now.isoformat(),
            })

        return escalation

    def get_escalation(self, message_id: str) -> Optional[Escalation]:
        """Retrieve escalation record by message ID."""
        return self.escalations.get(message_id)

    def list_pending_escalations(self) -> list[Escalation]:
        """
        List all pending escalations (no Z2 response yet).

        Returns:
            List of Escalation objects awaiting Z2 decision
        """
        return [
            esc for esc in self.escalations.values()
            if esc.z2_response is None
        ]

    def list_expired_escalations(self) -> list[Escalation]:
        """
        List escalations that exceeded 48h window without Z2 response.

        Returns:
            List of Escalation objects past timeout
        """
        now = datetime.now(timezone.utc)
        return [
            esc for esc in self.escalations.values()
            if esc.z2_response is None and now > datetime.fromisoformat(esc.timeout_at.replace('Z', '+00:00'))
        ]


if __name__ == "__main__":
    contract = EscalationContract()

    # Test escalation
    escalation = contract.escalate_to_human_required(
        "msg_001",
        445,
        "SIGNATURE_INVALID",
        "Message signature does not match sender node's public key"
    )
    print(f"Escalated: {escalation.message_id} (timeout: {escalation.timeout_at})")

    # Check timeout
    is_timeout = contract.check_timeout("msg_001")
    print(f"Timeout exceeded: {is_timeout}")

    # Resolve with Z2 decision
    escalation = contract.resolve_with_z2_decision(
        "msg_001",
        "REJECT",
        "Signature verification failed; message rejected."
    )
    print(f"Resolved by Z2: {escalation.z2_response}")
