QUESTIONS = [
    {
        "id": "tribal_citizen",
        "label": "Are you currently an enrolled citizen/member of a federally recognized tribe?",
        "type": "boolean",
        "required": True,
    },
    {
        "id": "tribe",
        "label": "Which tribe?",
        "type": "select",
        "options": ["Cherokee Nation", "Other federally recognized tribe", "Unknown / not listed"],
        "show_if": {"field": "tribal_citizen", "eq": True},
    },
    {
        "id": "resides_cn_jurisdiction_6m",
        "label": "Have you lived within Cherokee Nation jurisdiction for the past six months?",
        "type": "boolean",
        "show_if": {"field": "tribe", "eq": "Cherokee Nation"},
    },
    {
        "id": "outside_cn_reservation",
        "label": "Do you currently live outside the Cherokee Nation Reservation?",
        "type": "boolean",
        "show_if": {"field": "tribe", "eq": "Cherokee Nation"},
    },
    {"id": "business_owner", "label": "Do you own a business?", "type": "boolean"},
    {
        "id": "business_indian_ownership_percent",
        "label": "What percentage of the business is Indian-owned?",
        "type": "number",
        "min": 0,
        "max": 100,
        "show_if": {"field": "business_owner", "eq": True},
    },
    {
        "id": "business_active_control",
        "label": "Does the Indian owner actively operate and control the business?",
        "type": "boolean",
        "show_if": {"field": "business_owner", "eq": True},
    },
    {
        "id": "business_seeks_capital",
        "label": "Is the business seeking capital for startup or expansion?",
        "type": "boolean",
        "show_if": {"field": "business_owner", "eq": True},
    },
    {"id": "undergraduate", "label": "Are you pursuing an undergraduate degree?", "type": "boolean"},
    {
        "id": "first_associate_or_bachelors",
        "label": "Is this your first associate's or bachelor's degree?",
        "type": "boolean",
        "show_if": {"field": "undergraduate", "eq": True},
    },
    {
        "id": "fafsa_applied",
        "label": "Have you applied for federal student aid (FAFSA/Pell)?",
        "type": "boolean",
        "show_if": {"field": "undergraduate", "eq": True},
    },
    {"id": "needs_vocational_training", "label": "Are you seeking short-term vocational training or a professional credential?", "type": "boolean"},
    {"id": "insufficient_resources", "label": "Are household resources currently insufficient for essential living needs?", "type": "boolean"},
    {"id": "housing_finance_need", "label": "Are you seeking financing to buy, build, rehabilitate, or refinance a primary home?", "type": "boolean"},
    {
        "id": "housing_state",
        "label": "In which U.S. state is the property?",
        "type": "text",
        "show_if": {"field": "housing_finance_need", "eq": True},
    },
    {
        "id": "housing_county",
        "label": "In which county is the property?",
        "type": "text",
        "show_if": {"field": "housing_finance_need", "eq": True},
    },
    {"id": "iim_account_known", "label": "Do you already know that you have an Individual Indian Money (IIM) account?", "type": "boolean"},
    {"id": "dawes_ancestor_known", "label": "Do you know of an ancestor on a Cherokee Dawes final roll?", "type": "boolean"},
    {
        "id": "deceased_ancestor_possible_trust_assets",
        "label": "Is there a deceased Native ancestor who may have owned trust/restricted land or trust funds?",
        "type": "boolean",
    },
    {
        "id": "ancestor_allotment_or_land_clue",
        "label": "Do you have an allotment number, legal land description, probate order, lease/royalty statement, or other trust-land clue?",
        "type": "boolean",
        "show_if": {"field": "deceased_ancestor_possible_trust_assets", "eq": True},
    },
]
