#!/usr/bin/env python3
"""
intent_os_pages_v1_0.py — the Intent-OS board's section pages, generated from the board.
HumanAIOS · Builder · 2026-09-19

The board (ui/intent-os-humanaios-v3_3.html) is the one canonical file: its `const HUMANAIOS = {…};` block
carries the data, its seals are what tools/intent_os_board_check_v1_0.py re-hashes, and its filename is
frozen (d19). Z2 asked (2026-09-19) for four of its sections to be pages of their own, wired into a Witness
navigation: ARENA, Decisions, Commitments, Verified records. Copying data into four files would make four
things to keep in step; loading the board's data across files does not work from file://. So each page is
the board itself with a view: the same bytes, `<body data-view="…">` set, the title changed, and a
`<link rel="canonical">` naming the board. The board's own CSS hides the sections that belong to the other
views; the nav (inline in the board, the canonical source) carries the reader between them; taps, saved
state and the relay work identically on every page because the script is the same script.

The pages are derived files, like Z1_INBOX_INDEX.md: regenerate after every board change, and `--check`
fails when a page is not what the board would generate. Nothing is sealed here — the board is.

  python3 tools/intent_os_pages_v1_0.py            # write the four pages
  python3 tools/intent_os_pages_v1_0.py --check    # exit 2 if any page is out of date
  python3 tools/intent_os_pages_v1_0.py --self-test
"""
import os, re, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOARD = os.path.join("ui", "intent-os-humanaios-v3_3.html")
BOARD_NAME = os.path.basename(BOARD)
PAGES = {  # view key → (file, <title>)
    "decisions":   ("ui/intent-os-decisions.html",   "Intent-OS — Decisions"),
    "commitments": ("ui/intent-os-commitments.html", "Intent-OS — Commitments"),
    "records":     ("ui/intent-os-records.html",     "Intent-OS — Verified records"),
    "arena":       ("ui/intent-os-arena.html",       "Intent-OS — ARENA"),
}
TITLE_RE = re.compile(r"<title>.*?</title>", re.S)
BODY_RE = re.compile(r"<body(?: data-view=\"[a-z]+\")?>")
STAMP = "<!-- generated by tools/intent_os_pages_v1_0.py from %s — do not edit; regenerate -->"


def render_page(board_html: str, view: str, title: str) -> str:
    if not BODY_RE.search(board_html):
        raise ValueError("board has no <body> tag")
    if not TITLE_RE.search(board_html):
        raise ValueError("board has no <title>")
    if 'data-view' not in board_html or 'sec-' not in board_html:
        raise ValueError("board carries no section views (sec-* / data-view): pages would be whole copies")
    out = TITLE_RE.sub(f"<title>{title}</title>", board_html, count=1)
    out = BODY_RE.sub(f'<body data-view="{view}">', out, count=1)
    canon = f'<link rel="canonical" href="{BOARD_NAME}"/>\n{STAMP % BOARD_NAME}\n</head>'
    if "</head>" not in out:
        raise ValueError("board has no </head>")
    out = out.replace("</head>", canon, 1)
    return out


def expected() -> dict:
    with open(os.path.join(ROOT, BOARD), encoding="utf-8") as fh:
        board = fh.read()
    return {rel: render_page(board, view, title) for view, (rel, title) in PAGES.items()}


def write() -> int:
    for rel, html in expected().items():
        with open(os.path.join(ROOT, rel), "w", encoding="utf-8") as fh:
            fh.write(html)
        print(f"wrote {rel}")
    return 0


def check() -> int:
    stale = []
    for rel, html in expected().items():
        full = os.path.join(ROOT, rel)
        cur = open(full, encoding="utf-8").read() if os.path.isfile(full) else None
        state = "in sync" if cur == html else ("MISSING" if cur is None else "STALE")
        print(f"{rel}: {state}")
        if cur != html:
            stale.append(rel)
    if stale:
        print(f"{len(stale)} page(s) out of date — run: python3 tools/intent_os_pages_v1_0.py")
        return 2
    return 0


def self_test() -> int:
    board = ('<!DOCTYPE html><html><head><title>Board</title>\n<style>body[data-view="x"] .sec-y{display:none}</style>'
             '</head>\n<body>\n<section class="sec sec-x">x</section><section class="sec sec-y">y</section>\n'
             '<script>const HUMANAIOS = {\n rev:"1"\n};</script></body></html>')
    p = render_page(board, "decisions", "T")
    assert '<body data-view="decisions">' in p and "<title>T</title>" in p, p
    assert p.count("<body") == 1 and p.count("<title>") == 1
    assert f'<link rel="canonical" href="{BOARD_NAME}"/>' in p and "generated by tools/intent_os_pages_v1_0.py" in p
    assert "const HUMANAIOS = {" in p, "the data block must survive untouched"
    # idempotent: rendering a rendered page yields the same page (body/title/canonical replaced, not stacked)
    p2 = render_page(p.replace(f'<link rel="canonical" href="{BOARD_NAME}"/>\n{STAMP % BOARD_NAME}\n', ""), "decisions", "T")
    assert p2 == p, "not idempotent"
    for bad in ("<html><body>no title</body></html>", "<html><head><title>t</title></head>no body</html>",
                '<html><head><title>t</title></head><body>no views</body></html>'):
        try:
            render_page(bad, "decisions", "T"); raise AssertionError("accepted a board it should refuse: " + bad)
        except ValueError:
            pass
    # check() sees a stale page and a fresh one
    with tempfile.TemporaryDirectory() as td:
        global ROOT
        keep = ROOT; ROOT = td
        try:
            os.makedirs(os.path.join(td, "ui"))
            open(os.path.join(td, BOARD), "w").write(board)
            assert check() == 2, "missing pages must fail --check"
            assert write() == 0 and check() == 0, "written pages must pass --check"
            open(os.path.join(td, PAGES["arena"][0]), "a").write("<!-- edited by hand -->")
            assert check() == 2, "a hand-edited page must fail --check"
        finally:
            ROOT = keep
    print("SELF-TEST PASS")
    return 0


if __name__ == "__main__":
    a = sys.argv[1:]
    if "--self-test" in a:
        sys.exit(self_test())
    if "--check" in a:
        sys.exit(check())
    sys.exit(write())
