#!/usr/bin/env python3
"""intent_os_pages — the Intent-OS board's section pages, generated from the board.
Builder v1.7 compliant · template_tool
HumanAIOS · S-091926-01 (Z2, 2026-09-19: four sections of the board as their own pages, wired into a
Witness navigation built for Intent-OS)

The board (ui/intent-os-humanaios-v3_3.html) is the one canonical file: its `const HUMANAIOS = {…};` block
carries the data, its seals are what tools/intent_os_board_check_v1_0.py re-hashes, and its filename is
frozen (d19). Copying data into four files would make four things to keep in step; loading the board's
data across files does not work from file://. So each page is the board itself with a view: the same
bytes, `<body data-view="…">` set, the title changed, and a `<link rel="canonical">` naming the board. The
board's own CSS hides the sections that belong to the other views; the nav (inline in the board, the
canonical source) carries the reader between them; taps, saved state and the relay work identically on
every page because the script is the same script.

The pages are derived files, like Z1_INBOX_INDEX.md: regenerate after every board change, and `--check`
fails when a page is not what the board would generate. Nothing is sealed here — the board is.

  python3 tools/intent_os_pages_v1_0.py                 # write the four pages from the board
  python3 tools/intent_os_pages_v1_0.py --check         # exit 2 if any page is out of date
  python3 tools/intent_os_pages_v1_0.py --input ui/intent-os-humanaios-v3_3.html   # another board file
  python3 tools/intent_os_pages_v1_0.py --smoke-test    # (= --self-test) no network, temp dir
  python3 tools/intent_os_pages_v1_0.py --help

Every run writes a JSON report to outputs/ (write_report). Exit: 0 ok · 1 usage / a board that cannot
be rendered (SpecLoadFailed) · 2 a stale page under --check, or a failed self-test.
"""
import argparse
import datetime
import json
import os
import re
import sys
import tempfile

TOOL_NAME = "intent_os_pages"
TOOL_VERSION = "1.0.0"
TOOL_CATEGORY = "template_tool"
TOOL_SESSION = "S-091926-01"
TOOL_ZONE = 1  # 1=execute: derives files from the board; decides nothing, signs nothing

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOARD = os.path.join("ui", "intent-os-humanaios-v3_3.html")
BOARD_NAME = os.path.basename(BOARD)
PAGES = {  # view key → (file, <title>)
    "decisions":   ("ui/intent-os-decisions.html",   "Intent-OS — Decisions"),
    "commitments": ("ui/intent-os-commitments.html", "Intent-OS — Commitments"),
    "records":     ("ui/intent-os-records.html",     "Intent-OS — Verified records"),
    "arena":       ("ui/intent-os-arena.html",       "Intent-OS — ARENA"),
}
TITLE_RE = re.compile(r"<title>.*?</title>", re.S)
BODY_RE = re.compile(r"<body(?: data-view=\"[a-z]+\")?>")
ANY_BODY_RE = re.compile(r"<body\b", re.I)
STAMP = "<!-- generated by tools/intent_os_pages_v1_0.py from %s — do not edit; regenerate -->"
CANON_RE = re.compile(r'<link rel="canonical" href="[^"]*"/>\n<!-- generated by tools/intent_os_pages_v1_0\.py from [^\n]*-->\n')
ANY_CANON_RE = re.compile(r'<link[^>]*rel=["\']canonical["\']', re.I)  # either quote style
VIEW_CSS_RE = re.compile(r'body\[data-view=["\']([a-z]+)["\']\]')  # every view the board's CSS knows, either quote style


class SpecLoadFailed(Exception):
    """The board cannot be rendered into pages: no <title>, no <body>, no </head>, or no section views."""


def render_page(board_html: str, view: str, title: str) -> str:
    """One page from the board's bytes. Idempotent: rendering a rendered page gives the same page."""
    if view not in PAGES and view != "board":
        raise SpecLoadFailed(f"unknown view {view!r}; views are {sorted(PAGES)}")
    if not BODY_RE.search(board_html):
        raise SpecLoadFailed("board has no <body> tag")
    if not TITLE_RE.search(board_html):
        raise SpecLoadFailed("board has no <title>")
    if "</head>" not in board_html:
        raise SpecLoadFailed("board has no </head>")
    if "data-view" not in board_html or "sec-" not in board_html:
        raise SpecLoadFailed("board carries no section views (sec-* / data-view): pages would be whole copies")
    if len(ANY_BODY_RE.findall(board_html)) != 1:
        raise SpecLoadFailed("board has more than one <body>: the view attribute would land on the wrong one")
    # every view the board's CSS knows must be a page this tool writes (or the board itself): a view added to
    # the board without a PAGES entry would otherwise be silently unreachable
    unknown = sorted(set(VIEW_CSS_RE.findall(board_html)) - set(PAGES) - {"board"})
    if unknown:
        raise SpecLoadFailed(f"board CSS names views this tool does not write: {unknown} — add them to PAGES")
    out = CANON_RE.sub("", board_html, count=1)  # a previously rendered page renders again, not twice
    if ANY_CANON_RE.search(out):
        raise SpecLoadFailed("board already carries a canonical link that is not this tool's stamp; a page would carry two")
    out = TITLE_RE.sub(f"<title>{title}</title>", out, count=1)
    out = BODY_RE.sub(f'<body data-view="{view}">', out, count=1)
    canon = f'<link rel="canonical" href="{BOARD_NAME}"/>\n{STAMP % BOARD_NAME}\n</head>'
    out = out.replace("</head>", canon, 1)
    assert len(ANY_CANON_RE.findall(out)) == 1 and len(ANY_BODY_RE.findall(out)) == 1 and out.count("<title>") == 1
    return out


def expected(root: str, board_rel: str = BOARD) -> dict:
    full = os.path.join(root, board_rel)
    if not os.path.isfile(full):
        raise SpecLoadFailed(f"board not found: {board_rel}")
    with open(full, encoding="utf-8") as fh:
        board = fh.read()
    return {rel: render_page(board, view, title) for view, (rel, title) in PAGES.items()}


def write_pages(root: str, board_rel: str = BOARD) -> dict:
    rows = []
    for rel, html in expected(root, board_rel).items():
        with open(os.path.join(root, rel), "w", encoding="utf-8") as fh:
            fh.write(html)
        rows.append({"page": rel, "state": "written", "bytes": len(html.encode("utf-8"))})
        print(f"wrote {rel}")
    return {"mode": "write", "pages": rows, "stale": 0}


def check_pages(root: str, board_rel: str = BOARD) -> dict:
    rows, stale = [], 0
    for rel, html in expected(root, board_rel).items():
        full = os.path.join(root, rel)
        cur = open(full, encoding="utf-8").read() if os.path.isfile(full) else None
        state = "in sync" if cur == html else ("MISSING" if cur is None else "STALE")
        if cur != html:
            stale += 1
        rows.append({"page": rel, "state": state})
        print(f"{rel}: {state}")
    if stale:
        print(f"{stale} page(s) out of date — run: python3 tools/intent_os_pages_v1_0.py")
    return {"mode": "check", "pages": rows, "stale": stale}


def write_report(report: dict, root: str = ROOT, board: str = BOARD) -> str:
    """The run's JSON receipt under outputs/ (gitignored): what was rendered or checked, and the verdict."""
    out_dir = os.path.join(root, "outputs")
    os.makedirs(out_dir, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = os.path.join(out_dir, f"{TOOL_NAME}_{stamp}.json")
    body = {"tool": TOOL_NAME, "version": TOOL_VERSION, "category": TOOL_CATEGORY, "zone": TOOL_ZONE,
            "at": stamp, "board": board, **report}
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(body, fh, indent=1)
    return path


def run_smoke_test() -> int:
    """No network, a temp dir, a synthetic board: refusal, idempotence, a stale and a hand-edited page."""
    board = ('<!DOCTYPE html><html><head><title>Board</title>\n<style>body[data-view="decisions"] .sec-y{display:none}</style>'
             '</head>\n<body data-view="board">\n<section class="sec sec-x">x</section><section class="sec sec-y">y</section>\n'
             '<script>const HUMANAIOS = {\n rev:"1"\n};</script></body></html>')
    p = render_page(board, "decisions", "T")
    assert '<body data-view="decisions">' in p and "<title>T</title>" in p, p
    assert p.count("<body") == 1 and p.count("<title>") == 1 and p.count("canonical") == 1
    assert f'<link rel="canonical" href="{BOARD_NAME}"/>' in p and "generated by tools/intent_os_pages_v1_0.py" in p
    assert "const HUMANAIOS = {" in p, "the data block must survive untouched"
    assert render_page(p, "decisions", "T") == p, "not idempotent: rendering a rendered page changed it"
    assert render_page(p, "arena", "A").count("canonical") == 1, "re-rendering under another view stacked a canonical"
    head = '<html><head><title>t</title>'
    views = '<style>body[data-view="decisions"] .sec-y{display:none}</style>'
    for bad in ("<html><body>no title</body></html>", "<html><head><title>t</title></head>no body</html>",
                head + '</head><body>no views</body></html>',
                head + views + '</head><body><div>nested</div><body>second body</body></body></html>',
                head + views + '<link rel="canonical" href="https://elsewhere.example/"/></head><body><section class="sec sec-y">y</section></body></html>',
                head + '<style>body[data-view="ledger"] .sec-y{display:none}</style></head><body><section class="sec sec-y">y</section></body></html>',
                # the same two refusals with single-quoted attributes (Copilot on #411)
                head + views + "<link rel='canonical' href='https://elsewhere.example/'></head><body><section class='sec sec-y'>y</section></body></html>",
                head + "<style>body[data-view='ledger'] .sec-y{display:none}</style></head><body><section class='sec sec-y'>y</section></body></html>"):
        try:
            render_page(bad, "decisions", "T")
            raise AssertionError("accepted a board it should refuse: " + bad)
        except SpecLoadFailed:
            pass
    try:
        render_page(board, "nope", "T")
        raise AssertionError("accepted an unknown view")
    except SpecLoadFailed:
        pass
    with tempfile.TemporaryDirectory() as td:
        os.makedirs(os.path.join(td, "ui"))
        try:
            check_pages(td)
            raise AssertionError("a missing board must raise SpecLoadFailed")
        except SpecLoadFailed:
            pass
        open(os.path.join(td, BOARD), "w").write(board)
        assert check_pages(td)["stale"] == 4, "missing pages must count as stale"
        assert write_pages(td)["stale"] == 0 and check_pages(td)["stale"] == 0, "written pages must pass --check"
        open(os.path.join(td, PAGES["arena"][0]), "a").write("<!-- edited by hand -->")
        assert check_pages(td)["stale"] == 1, "a hand-edited page must fail --check"
        rp = write_report({"mode": "smoke"}, td)
        assert os.path.isfile(rp) and json.load(open(rp))["tool"] == TOOL_NAME
    print("SELF-TEST PASS")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="report stale pages; exit 2 if any (writes nothing)")
    g.add_argument("--smoke-test", "--self-test", dest="smoke", action="store_true", help="self-test in a temp dir")
    ap.add_argument("--input", default=BOARD, help="the board file, relative to the repository root")
    ap.add_argument("--root", default=ROOT, help=argparse.SUPPRESS)
    a = ap.parse_args()
    if a.smoke:
        return run_smoke_test()
    try:
        report = check_pages(a.root, a.input) if a.check else write_pages(a.root, a.input)
    except SpecLoadFailed as e:
        print(f"::error::{e}")
        write_report({"mode": "check" if a.check else "write", "error": str(e)}, a.root, a.input)
        return 1
    write_report(report, a.root, a.input)
    return 2 if report["stale"] and a.check else 0


if __name__ == "__main__":
    sys.exit(main())
