#!/usr/bin/env python3
"""
HumanAIOS PR Challenge Dialogue Router — v0.1.0
Builder v1.7 compliant · governance_tool
Session: CHALLENGE-DIALOGUE-001

Finite, idempotent red-team conversation routing for PR #630.
The router emits proposed PR comments only and grants no authority.
"""

from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path
from typing import Any

TOOL_NAME = "pr_challenge_dialogue_router"
TOOL_VERSION = "0.1.0"
TOOL_CATEGORY = "governance_tool"
TOOL_SESSION = "CHALLENGE-DIALOGUE-001"
TOOL_ZONE = 2

ROUTER_MARKER = "humanaios-challenge-router"
TURN_ORDER = {
    "AUDIT_RECEIVED": "SCOPE_CORRECTION",
    "SCOPE_CORRECTION": "EVIDENCE_CHALLENGE",
    "EVIDENCE_CHALLENGE": "DISPOSITION",
    "DISPOSITION": "COMPLETE",
}
FINDING_HEADER = re.compile(r"^####\s+([A-Z0-9][A-Z0-9._-]+)\s*:", re.M)
AUDITED_HEAD_PATTERNS = (
    re.compile(r"\*\*Audited HEAD SHA:\*\*\s*`?([0-9a-f]{40})`?", re.I),
    re.compile(r"^audited_head:\s*`?([0-9a-f]{40})`?\s*$", re.I | re.M),
)
TURN_TYPE_RE = re.compile(r"^turn_type:\s*([A-Z_]+)\s*$", re.I | re.M)
CONVERSATION_ID_RE = re.compile(r"^conversation_id:\s*([A-Za-z0-9._:-]+)\s*$", re.I | re.M)
AUTHORITY_EFFECT_RE = re.compile(r"^authority_effect:\s*([A-Z_]+)\s*$", re.I | re.M)
ARTIFACT_RE = re.compile(r"^\*\*(?:Affected Artifact|Artifact):\*\*\s*(.+?)\s*$", re.I | re.M)
CODE_PATH_RE = re.compile(r"`([^`]+)`")

def is_positive_claude_turn(body: str) -> bool:
    low = body.lower()
    return (
        ("auditor origin:" in low and "claude code" in low)
        or "generated by [claude code]" in low
        or "generated by claude code" in low
    )

def extract_audited_head(body: str) -> str | None:
    for pattern in AUDITED_HEAD_PATTERNS:
        match = pattern.search(body)
        if match:
            return match.group(1).lower()
    return None

def extract_turn_type(body: str) -> str:
    match = TURN_TYPE_RE.search(body)
    return match.group(1).upper() if match else "AUDIT_RECEIVED"

def extract_conversation_id(body: str, pr_number: int) -> str:
    match = CONVERSATION_ID_RE.search(body)
    return match.group(1) if match else f"PR{pr_number}-REDTEAM-001"

def authority_effect_is_none(body: str, turn_type: str) -> bool:
    match = AUTHORITY_EFFECT_RE.search(body)
    if match:
        return match.group(1).upper() == "NONE"
    return turn_type == "AUDIT_RECEIVED" and bool(
        re.search(r"Authority Effect:\*\*\s*NONE", body, re.I)
    )

def split_finding_blocks(body: str) -> list[tuple[str, str]]:
    matches = list(FINDING_HEADER.finditer(body))
    out = []
    for i, match in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        out.append((match.group(1), body[match.start():end]))
    return out

def artifact_paths(block: str) -> list[str]:
    match = ARTIFACT_RE.search(block)
    if not match:
        return []
    text = match.group(1)
    coded = [x.strip() for x in CODE_PATH_RE.findall(text) if x.strip()]
    if coded:
        return coded
    return [
        x.strip().strip("`")
        for x in re.split(r"\s*\+\s*|,\s*", text)
        if "/" in x or x.strip().startswith(".")
    ]

def classify_scope(body: str, changed_files: set[str]) -> list[dict[str, Any]]:
    rows = []
    for finding_id, block in split_finding_blocks(body):
        paths = artifact_paths(block)
        direct = sorted(path for path in paths if path in changed_files)
        rows.append({
            "finding_id": finding_id,
            "artifacts": paths,
            "direct_changed_artifacts": direct,
            "router_scope": (
                "IN_SCOPE_PR630_FINDING" if direct else
                "OUT_OF_SCOPE_REPOSITORY_FINDING" if paths else
                "UNRESOLVED_SCOPE"
            ),
        })
    return rows

def processed_source_ids(comments: list[dict[str, Any]]) -> set[int]:
    ids = set()
    pattern = re.compile(
        r"<!--\s*" + re.escape(ROUTER_MARKER) + r"\s+(\{.*?\})\s*-->", re.S
    )
    for comment in comments:
        for match in pattern.finditer(str(comment.get("body") or "")):
            try:
                payload = json.loads(match.group(1))
            except json.JSONDecodeError:
                continue
            if isinstance(payload.get("source_comment_id"), int):
                ids.add(payload["source_comment_id"])
    return ids

def scope_table(findings: list[dict[str, Any]]) -> str:
    if not findings:
        return "_No structured finding headings were parsed._"
    lines = ["| Finding | Router scope | Direct changed artifact |",
             "| --- | --- | --- |"]
    for item in findings:
        direct = ", ".join(f"`{p}`" for p in item["direct_changed_artifacts"]) or "—"
        lines.append(f"| {item['finding_id']} | {item['router_scope']} | {direct} |")
    return "\n".join(lines)

def marker_payload(repository: str, pr: int, conversation_id: str,
                   source_id: int, audited_head: str | None,
                   current_head: str, state: str, next_turn: str | None) -> dict[str, Any]:
    logical = f"{repository}|{pr}|{conversation_id}|{source_id}"
    return {
        "schema": "humanaios.challenge-router.v0.1",
        "event_key": hashlib.sha256(logical.encode()).hexdigest(),
        "repository": repository,
        "pr": pr,
        "conversation_id": conversation_id,
        "source_comment_id": source_id,
        "audited_head": audited_head,
        "current_head": current_head,
        "state": state,
        "next_turn": next_turn,
        "authority_effect": "NONE",
    }

def render_prompt(payload: dict[str, Any], findings: list[dict[str, Any]]) -> str:
    marker = "<!-- " + ROUTER_MARKER + " " + json.dumps(
        payload, sort_keys=True, separators=(",", ":")
    ) + " -->"
    cid = payload["conversation_id"]
    audited = payload["audited_head"]
    current = payload["current_head"]
    next_turn = payload["next_turn"]

    if payload["state"] == "HEAD_MISMATCH":
        return f"""{marker}
## Challenge router — HEAD mismatch

The Claude turn is bound to `{audited or 'UNKNOWN'}`, while this PR currently points to `{current}`.
No findings are translated forward automatically.

@claude Please either keep the response explicitly bound to the older head, or re-audit the current head.

```text
conversation_id: {cid}
turn_type: SCOPE_CORRECTION
audited_head: {current}
authority_effect: NONE
```

`router != authority · authority_effect = NONE`
"""

    if payload["state"] == "MALFORMED_TURN":
        return f"""{marker}
## Challenge router — malformed turn

@claude Please return the same substantive evidence with the required machine footer:

```text
conversation_id: {cid}
turn_type: {next_turn or 'SCOPE_CORRECTION'}
audited_head: {audited or current}
authority_effect: NONE
```

`router != authority · authority_effect = NONE`
"""

    if next_turn == "SCOPE_CORRECTION":
        return f"""{marker}
## Challenge router — audit received

Head binding: `{audited}` = current PR head `{current}`.

### Mechanical changed-file scope

{scope_table(findings)}

The router only distinguishes direct changed-file scope; it does not decide dependency or transitive relevance.

@claude Reclassify every finding as exactly one of:

```text
IN_SCOPE_PR630_FINDING
PR630_TRANSITIVE_RISK
DEPENDENCY_FINDING
OUT_OF_SCOPE_REPOSITORY_FINDING
```

For each non-direct finding, name the dependency edge that makes it relevant to this PR, if one exists, and state whether it should block this PR, open a separate issue, or remain informational.

```text
conversation_id: {cid}
turn_type: SCOPE_CORRECTION
audited_head: {audited}
authority_effect: NONE
```

`router != authority · challenge != defect · authority_effect = NONE`
"""

    if next_turn == "EVIDENCE_CHALLENGE":
        return f"""{marker}
## Challenge router — scope correction received

@claude For findings still relevant to this PR, provide independent reproduction evidence:
- exact artifact/code path;
- command or deterministic test;
- expected vs observed result;
- falsifier;
- uncertainty;
- overlap/divergence from Copilot, without adopting Copilot findings as your own.

```text
conversation_id: {cid}
turn_type: EVIDENCE_CHALLENGE
audited_head: {audited}
authority_effect: NONE
```

`router != authority · evidence != warrant · authority_effect = NONE`
"""

    if next_turn == "DISPOSITION":
        return f"""{marker}
## Challenge router — evidence challenge received

@claude Return a finding-by-finding proposed disposition using only:

```text
SUPPORTED
NOT_REPRODUCED
REBUTTED
REMEDIATED
ACCEPTED_RESIDUAL
OUT_OF_SCOPE
SUPERSEDED
```

Include evidence reference, remediation/retest requirement, separate-issue ownership if applicable, and residual uncertainty. Do not imply merge authorization.

```text
conversation_id: {cid}
turn_type: DISPOSITION
audited_head: {audited}
authority_effect: NONE
```

`router != authority · disposition != merge decision · authority_effect = NONE`
"""

    return f"""{marker}
## Challenge router — conversation complete

The structured red-team conversation `{cid}` is complete for audited head `{audited}`.
No merge, approval, remediation, or authority action was taken.

```text
conversation_id: {cid}
turn_type: COMPLETE
audited_head: {audited}
authority_effect: NONE
```

Next step: integrate preserved challenge evidence into a revised warrant under ordinary human authority.
"""

def route(*, event: dict[str, Any], changed_files: set[str],
          existing_comments: list[dict[str, Any]], current_head: str,
          repository: str, pilot_pr: int = 630) -> dict[str, Any]:
    if str(event.get("action") or "") not in {"created", "edited"}:
        return {"should_reply": False, "reason": "unsupported_action"}
    issue = event.get("issue") or {}
    if "pull_request" not in issue:
        return {"should_reply": False, "reason": "not_pull_request"}
    pr = int(issue.get("number") or 0)
    if pr != pilot_pr:
        return {"should_reply": False, "reason": "not_pilot_pr"}

    comment = event.get("comment") or {}
    source_id = int(comment.get("id") or 0)
    body = str(comment.get("body") or "")
    if not source_id or not is_positive_claude_turn(body):
        return {"should_reply": False, "reason": "not_positive_claude_turn"}
    if source_id in processed_source_ids(existing_comments):
        return {"should_reply": False, "reason": "duplicate_source_comment"}

    cid = extract_conversation_id(body, pr)
    turn_type = extract_turn_type(body)
    audited = extract_audited_head(body)
    findings = classify_scope(body, changed_files)

    if not authority_effect_is_none(body, turn_type) or not audited:
        state, next_turn = "MALFORMED_TURN", "SCOPE_CORRECTION"
    elif audited != current_head.lower():
        state, next_turn = "HEAD_MISMATCH", "SCOPE_CORRECTION"
    elif turn_type == "COMPLETE":
        return {"should_reply": False, "reason": "terminal_complete"}
    elif turn_type not in TURN_ORDER:
        state, next_turn = "MALFORMED_TURN", "SCOPE_CORRECTION"
    else:
        state, next_turn = turn_type, TURN_ORDER[turn_type]

    payload = marker_payload(repository, pr, cid, source_id, audited,
                             current_head.lower(), state, next_turn)
    return {
        "should_reply": True,
        "reason": "routed",
        "state": state,
        "next_turn": next_turn,
        "conversation_id": cid,
        "audited_head": audited,
        "findings": findings,
        "comment": render_prompt(payload, findings),
        "marker": payload,
    }

def _load(path: Path) -> Any:
    return json.loads(path.read_text())

def smoke_test() -> int:
    head = "a" * 40
    body = f"""## RED TEAM AUDIT
**Auditor Origin:** Claude Code
**Audited HEAD SHA:** `{head}`
**Authority Effect:** NONE
#### TEST-001: example
**Affected Artifact:** `tools/a.py`
_Generated by [Claude Code](https://claude.ai/code)_
"""
    event = {"action": "created", "issue": {"number": 630, "pull_request": {}},
             "comment": {"id": 10, "body": body}}
    result = route(event=event, changed_files={"tools/a.py"},
                   existing_comments=[], current_head=head,
                   repository="humanaios-ui/operations")
    assert result["should_reply"]
    assert result["next_turn"] == "SCOPE_CORRECTION"
    assert result["findings"][0]["router_scope"] == "IN_SCOPE_PR630_FINDING"
    duplicate = route(event=event, changed_files={"tools/a.py"},
                      existing_comments=[{"body": result["comment"]}],
                      current_head=head, repository="humanaios-ui/operations")
    assert duplicate == {"should_reply": False, "reason": "duplicate_source_comment"}
    print("smoke-test OK")
    return 0

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--event", type=Path)
    parser.add_argument("--changed-files", type=Path)
    parser.add_argument("--existing-comments", type=Path)
    parser.add_argument("--current-head")
    parser.add_argument("--repository")
    parser.add_argument("--pilot-pr", type=int, default=630)
    parser.add_argument("--smoke-test", action="store_true")
    args = parser.parse_args()
    if args.smoke_test:
        return smoke_test()
    if not all([args.event, args.changed_files, args.existing_comments,
                args.current_head, args.repository]):
        parser.error("required inputs missing")
    changed = {x.strip() for x in args.changed_files.read_text().splitlines() if x.strip()}
    existing = _load(args.existing_comments)
    result = route(event=_load(args.event), changed_files=changed,
                   existing_comments=existing, current_head=args.current_head,
                   repository=args.repository, pilot_pr=args.pilot_pr)
    print(json.dumps(result, sort_keys=True))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())