#!/usr/bin/env python3
"""smag_gap_analysis — the ANALYZE step of the recursive-learning loop.

Reads the consolidated SMAG ledger and computes the predicted-vs-measured GAP.
This is ACAT's own methodology turned on the repo itself: a PR's *predicted*
delivery (the author's self-report, a Phase-1 analogue) vs its *measured* outcome
(merge + CI checks, a Phase-3 behavioural analogue). The gap between them is the
Learning-Index analogue at the PR surface.

v1 is the mechanical tier (no LLM). The signal it computes:
  clean   = merged AND zero failing checks            (self-report matched behaviour)
  friction= merged BUT one or more failing checks     (delivered, but not as claimed)
  miss    = not merged                                (predicted deliver, didn't land)

Aggregates by substrate (human / Copilot / Claude / …) and overall, so a recurring
gap pattern (e.g. one substrate systematically shipping with failing checks) becomes
visible — the input the FEED-BACK step writes to lessons_learned_ledger / promotes to
a behavioural gate.

Usage:
  python3 smag_gap_analysis_v1_0.py [--ledger audits/smag_pilot_ledger.jsonl]
                                    [--out audits/smag_gap_report.md] [--json]
  python3 smag_gap_analysis_v1_0.py --smoke-test
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

# Builder v1.7 compliant
# HumanAIOS
TOOL_NAME = "smag_gap_analysis"
TOOL_VERSION = "1.0.0"
DEFAULT_LEDGER = "audits/smag_pilot_ledger.jsonl"
DEFAULT_OUT = "audits/smag_gap_report.md"

_MERGED = re.compile(r"merged\s*=\s*(True|False)", re.IGNORECASE)
_FAIL = re.compile(r"failure:\s*(\d+)")


# --- pure classification (testable) ------------------------------------------
def classify(measured: str) -> str:
    """clean | friction | miss | unknown, from the measured string."""
    m = _MERGED.search(measured or "")
    if not m:
        return "unknown"
    merged = m.group(1).lower() == "true"
    if not merged:
        return "miss"
    f = _FAIL.search(measured or "")
    fails = int(f.group(1)) if f else 0
    return "friction" if fails > 0 else "clean"


def analyze(rows: list[dict]) -> dict:
    """Overall + per-substrate gap tallies and rates."""
    buckets = ["clean", "friction", "miss", "unknown"]
    overall = dict.fromkeys(buckets, 0)
    by_sub: dict = defaultdict(lambda: dict.fromkeys(buckets, 0))
    for r in rows:
        v = classify(r.get("measured", ""))
        overall[v] += 1
        by_sub[r.get("substrate", "unknown")][v] += 1

    def rates(d: dict) -> dict:
        graded = d["clean"] + d["friction"] + d["miss"]  # unknown excluded from denom
        gap = d["friction"] + d["miss"]
        return {
            "n": sum(d.values()),
            "graded": graded,
            "clean_rate": round(d["clean"] / graded, 3) if graded else None,
            "gap_rate": round(gap / graded, 3) if graded else None,
        }

    return {
        "n_rows": len(rows),
        "overall": {**overall, **rates(overall)},
        "by_substrate": {s: {**c, **rates(c)} for s, c in sorted(by_sub.items())},
    }


def render_md(a: dict) -> str:
    o = a["overall"]
    lines = [
        "# SMAG gap report (predicted vs measured)",
        "",
        f"_Generated by smag_gap_analysis v{TOOL_VERSION} over {a['n_rows']} ledger row(s)._",
        "",
        "**clean** = merged, no failing checks · **friction** = merged with failing "
        "checks · **miss** = not merged. gap_rate = (friction+miss)/graded.",
        "",
        "## Overall",
        "",
        f"- rows: {o['n']}  ·  graded: {o['graded']}",
        f"- clean: {o['clean']}  ·  friction: {o['friction']}  ·  miss: {o['miss']}  "
        f"·  unknown: {o['unknown']}",
        f"- **clean_rate: {o['clean_rate']}**  ·  **gap_rate: {o['gap_rate']}**",
        "",
        "## By substrate",
        "",
        "| substrate | n | clean | friction | miss | clean_rate | gap_rate |",
        "|---|---|---|---|---|---|---|",
    ]
    for s, c in a["by_substrate"].items():
        lines.append(f"| `{s}` | {c['n']} | {c['clean']} | {c['friction']} | "
                     f"{c['miss']} | {c['clean_rate']} | {c['gap_rate']} |")
    lines += [
        "",
        "## Feed-back cues (for lessons_learned_ledger / behavioural gates)",
        "",
        "- A substrate with a persistently high `gap_rate` is over-predicting delivery "
        "relative to measured CI/merge outcome — a calibration lesson to record.",
        "- `friction` rows (merged with failing checks) are the reward-hacking smell: "
        "shipped despite red — candidates for a hard behavioural-compliance gate.",
        "- Trend this report over time; success = gap_rate declining across rounds.",
        "",
    ]
    return "\n".join(lines)


# --- I/O ---------------------------------------------------------------------
def load_rows(path: Path) -> list[dict]:
    rows = []
    for line in (path.read_text(encoding="utf-8").splitlines() if path.exists() else []):
        line = line.strip()
        if line:
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return rows


def smoke_test() -> int:
    assert classify("merged=True; checks: failure:0, in_progress:0") == "clean"
    assert classify("merged=True; checks: failure:2, in_progress:4") == "friction"
    assert classify("merged=False; checks: failure:0") == "miss"
    assert classify("no info") == "unknown"
    a = analyze([
        {"substrate": "Copilot", "measured": "merged=True; checks: failure:0"},
        {"substrate": "Copilot", "measured": "merged=True; checks: failure:3"},
        {"substrate": "human:x", "measured": "merged=False"},
    ])
    assert a["overall"]["clean"] == 1 and a["overall"]["friction"] == 1 and a["overall"]["miss"] == 1
    assert a["overall"]["gap_rate"] == round(2 / 3, 3), a["overall"]["gap_rate"]
    assert a["by_substrate"]["Copilot"]["gap_rate"] == 0.5
    assert "SMAG gap report" in render_md(a)
    print("✓ Smoke test PASSED")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Analyze the SMAG predicted-vs-measured gap.")
    ap.add_argument("--ledger", default=DEFAULT_LEDGER)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--json", action="store_true", help="print JSON instead of writing the report")
    ap.add_argument("--smoke-test", action="store_true")
    args = ap.parse_args()
    if args.smoke_test:
        return smoke_test()
    rows = load_rows(Path(args.ledger))
    a = analyze(rows)
    if args.json:
        print(json.dumps(a, indent=2))
        return 0
    md = render_md(a)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(md, encoding="utf-8")
    print(f"smag_gap_analysis v{TOOL_VERSION}: {a['n_rows']} rows → {args.out}")
    print(f"  overall clean_rate={a['overall']['clean_rate']} gap_rate={a['overall']['gap_rate']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
