#!/usr/bin/env python3
"""
system_graph_render_v1_0.py — render system_graph.json to Markdown with a
provenance header, so every prose copy of the system graph points back at the
file and commit it was generated from.
Builder v1.7 compliant
HumanAIOS — Q-GRAPH-CAPTURE-LINT-01 follow-on (Drive ↔ GitHub graph sync)

WHY THIS EXISTS
system_graph.json is generated (system_graph_generator.py) and is the source
of record for the governance machinery's process graph. Prose copies of it
have been hand-written elsewhere (a Google Drive "system_graph_v0.2.md" dated
2026-10-02 carried 19 nodes and 44 edges while the source had 22 and 53).
A copy with no pointer back is P1 CLOSED_PROVENANCE in miniature: it reads as
authoritative and drifts silently. This renderer makes the copy mechanical and
stamps it with the source path, the source sha256, the generating commit and
the source's own generated_at, so a reader of the copy can check it against
the tree in one step.

USAGE
  python3 tools/system_graph_render_v1_0.py                 # Markdown to stdout
  python3 tools/system_graph_render_v1_0.py --out docs/SYSTEM_GRAPH.md
  python3 tools/system_graph_render_v1_0.py --check docs/SYSTEM_GRAPH.md
                                                            # exit 1 if stale
  --input <path>    a system graph other than system_graph.json
  --smoke-test      render an in-memory fixture; writes nothing

Direction rule this tool encodes: GitHub renders to Drive, not the reverse,
for anything the repo generates. Edit system_graph_generator.py or its inputs,
regenerate system_graph.json, re-render, then replace the Drive copy.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from collections import OrderedDict

TOOL_NAME = "system_graph_render"
TOOL_VERSION = "1.0.0"
TOOL_CATEGORY = "reporting_tool"
TOOL_SESSION = "S-100426-drive-graph-sync"
TOOL_ZONE = 1

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_INPUT = "system_graph.json"
STATUS_ORDER = ["OPERATED", "LAID", "PLANNED"]
EDGE_TYPE_ORDER = ["control_flow", "data_flow", "callout"]
EDGE_TYPE_TITLES = {"control_flow": "Control flow", "data_flow": "Data flow", "callout": "Callouts"}


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _git_head(root: str) -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, capture_output=True,
                             text=True, check=False)
        return out.stdout.strip() or "unknown"
    except OSError:
        return "unknown"


def render(graph: dict, *, source_path: str, source_sha256: str, commit: str) -> str:
    nodes = graph.get("nodes") or {}
    if isinstance(nodes, list):
        nodes = {n["id"]: n for n in nodes}
    edges = graph.get("edges") or []
    by_status: OrderedDict[str, list] = OrderedDict((s, []) for s in STATUS_ORDER)
    for nid in sorted(nodes):
        n = nodes[nid]
        by_status.setdefault(str(n.get("status", "UNKNOWN")), []).append(n)
    by_type: OrderedDict[str, list] = OrderedDict((t, []) for t in EDGE_TYPE_ORDER)
    for e in edges:
        by_type.setdefault(str(e.get("edge_type", "other")), []).append(e)

    out = []
    out.append(f"# HumanAIOS System Graph v{graph.get('version', '?')} (rendered)")
    out.append("")
    out.append("> **Rendered view. Do not edit.** Generated by "
               f"`tools/{TOOL_NAME}_v1_0.py` from `{source_path}`.")
    out.append(f"> Source `generated_at`: `{graph.get('generated_at', 'unknown')}` · "
               f"source sha256: `{source_sha256}` · rendered at commit `{commit}`.")
    out.append("> Edit `system_graph_generator.py` or its inputs, regenerate the JSON, re-render, "
               "then replace any copy of this page (Google Drive included).")
    out.append("")
    out.append(f"**Nodes:** {len(nodes)} · **Edges:** {len(edges)} · "
               + " · ".join(f"**{s}:** {len(v)}" for s, v in by_status.items() if v))
    vs = graph.get("validation_status") or {}
    if vs:
        out.append(f"**Generator validation:** valid={vs.get('valid')}; "
                   f"errors={vs.get('errors') or []}; warnings={vs.get('warnings') or []}")
    zd = graph.get("zone_distribution") or {}
    if zd:
        out.append("**Zone distribution:** " + ", ".join(f"{k}={v}" for k, v in sorted(zd.items())))
    out.append("")

    out.append("## Nodes")
    out.append("")
    for status, ns in by_status.items():
        if not ns:
            continue
        out.append(f"### {status} ({len(ns)})")
        out.append("")
        out.append("| id | name | type | zone | implementation | tests | phase | description |")
        out.append("|---|---|---|---|---|---|---|---|")
        for n in ns:
            desc = str(n.get("description", "")).replace("|", "\\|")
            out.append(f"| `{n.get('id')}` | {n.get('name', '')} | {n.get('type', '')} | "
                       f"{n.get('zone', '')} | `{n.get('implementation', '')}` | "
                       f"{n.get('tests', '')} | {n.get('phase', '')} | {desc} |")
        out.append("")

    out.append("## Edges")
    out.append("")
    for etype, es in by_type.items():
        if not es:
            continue
        out.append(f"### {EDGE_TYPE_TITLES.get(etype, etype)} ({len(es)})")
        out.append("")
        out.append("| from | to | label |")
        out.append("|---|---|---|")
        for e in sorted(es, key=lambda e: (str(e.get('source')), str(e.get('target')), str(e.get('label')))):
            label = str(e.get("label", "")).replace("|", "\\|")
            out.append(f"| `{e.get('source')}` | `{e.get('target')}` | {label} |")
        out.append("")

    out.append("## Provenance")
    out.append("")
    out.append(f"- source: `{source_path}` (sha256 `{source_sha256}`)")
    out.append("- generator of the source: `system_graph_generator.py`")
    out.append(f"- renderer: `tools/{TOOL_NAME}_v1_0.py` v{TOOL_VERSION}")
    out.append(f"- repository commit at render time: `{commit}`")
    out.append("- authority: this page is a view; node and edge changes are Z2 via blueprint "
               "(CLAUDE.md governance table, `system_graph.json` row)")
    out.append("")
    return "\n".join(out)


def render_file(input_path: str) -> str:
    with open(input_path, "rb") as fh:
        raw = fh.read()
    graph = json.loads(raw.decode("utf-8"))
    rel = os.path.relpath(os.path.abspath(input_path), ROOT).replace(os.sep, "/")
    return render(graph, source_path=rel, source_sha256=_sha256_bytes(raw), commit=_git_head(ROOT))


def _strip_commit_line(text: str) -> str:
    """--check ignores the commit stamp so a re-render on a later commit with an
    unchanged source does not read as drift; the source sha256 is what matters."""
    keep = []
    for line in text.splitlines():
        if "rendered at commit" in line or line.startswith("- repository commit at render time"):
            continue
        keep.append(line)
    return "\n".join(keep)


def run_smoke_test() -> int:
    fixture = {
        "version": "0.0", "generated_at": "2026-01-01T00:00:00",
        "nodes": {"A": {"id": "A", "name": "Alpha", "type": "process", "status": "OPERATED",
                        "zone": "Z1", "implementation": "a.py", "tests": 1, "phase": "M1",
                        "description": "pipe | in description"},
                  "B": {"id": "B", "name": "Beta", "type": "ledger", "status": "LAID",
                        "zone": "code", "implementation": "b.jsonl", "tests": 0, "phase": "M2",
                        "description": "x"}},
        "edges": [{"source": "A", "target": "B", "edge_type": "data_flow", "label": "rows"},
                  {"source": "B", "target": "A", "edge_type": "callout", "label": "GAP"}],
        "validation_status": {"valid": True, "errors": [], "warnings": []},
        "zone_distribution": {"Z1": 1, "code": 1},
    }
    md = render(fixture, source_path="fixture.json", source_sha256="deadbeef", commit="abc1234")
    assert "# HumanAIOS System Graph v0.0 (rendered)" in md
    assert "**Nodes:** 2 · **Edges:** 2" in md
    assert "### OPERATED (1)" in md and "### LAID (1)" in md and "PLANNED" not in md
    assert "pipe \\| in description" in md, "pipes inside cells must be escaped"
    assert "### Data flow (1)" in md and "### Callouts (1)" in md
    assert "sha256: `deadbeef`" in md and "commit `abc1234`" in md
    # --check semantics: a different commit stamp is not drift; a different source hash is
    md2 = render(fixture, source_path="fixture.json", source_sha256="deadbeef", commit="fff9999")
    assert _strip_commit_line(md) == _strip_commit_line(md2)
    md3 = render(fixture, source_path="fixture.json", source_sha256="00000000", commit="abc1234")
    assert _strip_commit_line(md) != _strip_commit_line(md3)
    # the real source, when present, renders without error and reports its real counts
    real = os.path.join(ROOT, DEFAULT_INPUT)
    if os.path.exists(real):
        with open(real, encoding="utf-8") as fh:
            g = json.load(fh)
        out = render_file(real)
        assert f"**Nodes:** {len(g['nodes'])} · **Edges:** {len(g['edges'])}" in out
    print(f"{TOOL_NAME} v{TOOL_VERSION} smoke test PASSED")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Render system_graph.json to Markdown with provenance.")
    ap.add_argument("--input", default=os.path.join(ROOT, DEFAULT_INPUT))
    ap.add_argument("--out", help="write the rendering here instead of stdout")
    ap.add_argument("--check", metavar="PATH", help="exit 1 if PATH differs from a fresh render "
                                                    "(commit stamp ignored)")
    ap.add_argument("--smoke-test", action="store_true")
    ap.add_argument("--version", action="version", version=f"{TOOL_NAME} {TOOL_VERSION}")
    args = ap.parse_args(argv)
    if args.smoke_test:
        return run_smoke_test()
    try:
        md = render_file(args.input)
    except (OSError, json.JSONDecodeError, KeyError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.check:
        try:
            with open(args.check, encoding="utf-8") as fh:
                current = fh.read()
        except OSError as exc:
            print(f"::error::{args.check}: {exc}", file=sys.stderr)
            return 1
        if _strip_commit_line(current.rstrip("\n")) != _strip_commit_line(md.rstrip("\n")):
            print(f"::error::{args.check} is out of sync with {args.input} — re-run "
                  f"tools/{TOOL_NAME}_v1_0.py --out {args.check}", file=sys.stderr)
            return 1
        print(f"{args.check}: in sync with {os.path.relpath(args.input, ROOT)}")
        return 0
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(md + "\n")
        print(f"wrote {args.out}")
        return 0
    sys.stdout.write(md + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
